species_1: human
species_2: mouse

species_1_peak_file: data/atac_seq_peaks/humanIDRConservedPeaks.gz
species_2_peak_file: data/atac_seq_peaks/mouseIDRConservedPeaks.gz

species_1_tss_file: data/tss_annotations/gencode.v41.annotation.bed
species_2_tss_file: data/tss_annotations/gencode.vM30.annotation.bed

species_1_to_species_2: results/alignment_results/human_to_mouse/human_liver.HumanToMouse.HALPER.narrowPeak.gz
species_2_to_species_1: results/alignment_results/mouse_to_human/mouse_liver.MouseToHuman.HALPER.narrowPeak.gz

output_dir: results/classification_results

parameters:
  promoter_distance: 2000